### ISSUE TITLE
Error while running the eval scripts on squad dataset using pre-trained models

### ISSUE THREAD

**Issue by vinaymundada27** [allenai/document-qa#7]
Tried running the `squad_full_document_eval.py` script **using the pre-trained models**. But getting the following error:

Command:
```
python docqa/eval/squad_full_document_eval.py -c dev docqa/models/squad output.csv
```
Error Log:
```
Loading data
Split 48 docs into 536115 paragraphs
Using best weights
Setting up model
Loading word vec glove.840B.300d for SquadCorpus from cache
Had pre-trained word embeddings for 26244 of 27612 words

2017-11-14 16:27:31.392041: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-11-14 16:27:31.392130: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-11-14 16:27:31.392162: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
tf session...
Traceback (most recent call last):
  File "/home/administrator/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/home/administrator/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1297, in _run_fn
    self._extend_graph()
  File "/home/administrator/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1358, in _extend_graph
    self._session, graph_def.SerializeToString(), status)
  File "/home/administrator/anaconda3/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/home/administrator/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'CudnnRNNParamsSize' with these attrs.  Registered devices: [CPU], Registered kernels:
  <no registered kernels>

         [[Node: map_embed/layer_1/forward/CudnnRNNParamsSize = CudnnRNNParamsSize[S=DT_INT32, T=DT_FLOAT, direction="unidirectional", dropout=0, input_mode="linear_input", rnn_mode="gru", seed=87654321, seed2=0](map_embed/layer_1/forward/CudnnRNNParamsSize/num_layers, map_embed/layer_1/forward/CudnnRNNParamsSize/num_units, map_embed/layer_1/forward/CudnnRNNParamsSize/input_size)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docqa/eval/squad_full_document_eval.py", line 213, in <module>
    main()
  File "docqa/eval/squad_full_document_eval.py", line 195, in main
    not args.no_ema, args.async)[args.corpus]
  File "/home/administrator/document-qa/docqa/trainer.py", line 658, in test
    pred = model.get_predictions_for(input_dict)
  File "/home/administrator/document-qa/docqa/doc_qa_models.py", line 110, in get_predictions_for
    return self._get_predictions_for(is_train, q_embed, q_mask, c_embed, c_mask, answer)
  File "/home/administrator/document-qa/docqa/doc_qa_models.py", line 190, in _get_predictions_for
    context_rep = self.embed_mapper.apply(is_train, context_rep, context_mask)
  File "/home/administrator/document-qa/docqa/nn/layers.py", line 403, in apply
    x = layer.apply(is_train, x, mask)
  File "/home/administrator/document-qa/docqa/nn/recurrent_layers.py", line 158, in apply
    return super().map(is_train, x, mask)
  File "/home/administrator/document-qa/docqa/nn/recurrent_layers.py", line 132, in map
    fw = self._apply_transposed(is_train, x)[0]
  File "/home/administrator/document-qa/docqa/nn/recurrent_layers.py", line 62, in _apply_transposed
    n_params = cell.params_size().eval()
  File "/home/administrator/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 541, in eval
    return _eval_using_default_session(self, feed_dict, self.graph, session)
  File "/home/administrator/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 4085, in _eval_using_default_session
    return session.run(tensors, feed_dict)
  File "/home/administrator/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/home/administrator/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/administrator/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/home/administrator/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'CudnnRNNParamsSize' with these attrs.  Registered devices: [CPU], Registered kernels:
  <no registered kernels>

         [[Node: map_embed/layer_1/forward/CudnnRNNParamsSize = CudnnRNNParamsSize[S=DT_INT32, T=DT_FLOAT, direction="unidirectional", dropout=0, input_mode="linear_input", rnn_mode="gru", seed=87654321, seed2=0](map_embed/layer_1/forward/CudnnRNNParamsSize/num_layers, map_embed/layer_1/forward/CudnnRNNParamsSize/num_units, map_embed/layer_1/forward/CudnnRNNParamsSize/input_size)]]

Caused by op 'map_embed/layer_1/forward/CudnnRNNParamsSize', defined at:
  File "docqa/eval/squad_full_document_eval.py", line 213, in <module>
    main()
  File "docqa/eval/squad_full_document_eval.py", line 195, in main
    not args.no_ema, args.async)[args.corpus]
  File "/home/administrator/document-qa/docqa/trainer.py", line 658, in test
    pred = model.get_predictions_for(input_dict)
  File "/home/administrator/document-qa/docqa/doc_qa_models.py", line 110, in get_predictions_for
    return self._get_predictions_for(is_train, q_embed, q_mask, c_embed, c_mask, answer)
  File "/home/administrator/document-qa/docqa/doc_qa_models.py", line 190, in _get_predictions_for
    context_rep = self.embed_mapper.apply(is_train, context_rep, context_mask)
  File "/home/administrator/document-qa/docqa/nn/layers.py", line 403, in apply
    x = layer.apply(is_train, x, mask)
  File "/home/administrator/document-qa/docqa/nn/recurrent_layers.py", line 158, in apply
    return super().map(is_train, x, mask)
  File "/home/administrator/document-qa/docqa/nn/recurrent_layers.py", line 132, in map
    fw = self._apply_transposed(is_train, x)[0]
  File "/home/administrator/document-qa/docqa/nn/recurrent_layers.py", line 62, in _apply_transposed
    n_params = cell.params_size().eval()
  File "/home/administrator/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/cudnn_rnn/python/ops/cudnn_rnn_ops.py", line 597, in params_size
    direction=self._direction)[0]
  File "/home/administrator/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/cudnn_rnn/ops/gen_cudnn_rnn_ops.py", line 286, in cudnn_rnn_params_size
    name=name)
  File "/home/administrator/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/administrator/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/administrator/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'CudnnRNNParamsSize' with these attrs.  Registered devices: [CPU], Registered kernels:
  <no registered kernels>

         [[Node: map_embed/layer_1/forward/CudnnRNNParamsSize = CudnnRNNParamsSize[S=DT_INT32, T=DT_FLOAT, direction="unidirectional", dropout=0, input_mode="linear_input", rnn_mode="gru", seed=87654321, seed2=0](map_embed/layer_1/forward/CudnnRNNParamsSize/num_layers, map_embed/layer_1/forward/CudnnRNNParamsSize/num_units, map_embed/layer_1/forward/CudnnRNNParamsSize/input_size)]]
```

**Comment by chrisc36** [comment]
This means your are trying to run the model on a machine without a GPU, or at least that tensorflow was not able to find your GPU. You need to either get a GPU running, or use the cpu-compatible models.

**Comment by vinaymundada27** [comment]
@chrisc36 Yeah that worked fine. Thanks a a lot!
